OverDeRheinKraanKeuringen/Models/Assignment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OverDeRheinKraanKeuringen.Models
{
    public class Assignment
    {
        public int Id { get; set; }

        [Display(Name = "Werkinstructie(s)")]
        //[Required(ErrorMessage = "Voer werkinstructie(s) in")]
        [MaxLength(500)]
        public string WorkInstruction { get; set; }

        [Display(Name = "Datum")]
        //[Required(ErrorMessage = "Voer een datum in")]
        [DataType(DataType.Date)] // This DataAnnotation is added to be able to save Date to the database
        public DateTime? Date { get; set; }

        [Display(Name = "Kabelleverancier")]
        //[Required(ErrorMessage = "Voer een kabelleverancier in")]
        [MaxLength(250)]
        public string CableSupplier { get; set; }

        [Display(Name = "Overige waarnemingen")]
        //[Required(ErrorMessage = "Voer overige waarnemingen in")]
        [MaxLength(500)]
        public string Observations { get; set; }

        [NotMapped]
        public string SignatureDataUrl { get; set; }

        [Display(Name = "Handtekening")]
        //[Required(ErrorMessage = "Voer een handtekening in")]
        public byte[] Signature { get; set; }

        [Display(Name = "Aantal bedrijfsuren")]
        [Required(ErrorMessage = "Voer het aantal bedrijfsuren in")]
        public uint OperatingHours { get; set; }

        [Display(Name = "Redenen voor het afleggen")]
        //[Required(ErrorMessage = "Voer redenen voor het afleggen in")]
        public string Reason { get; set; }

        public List<CableChecklist> CableChecklists { get; set; }
    }
}

OverDeRheinKraanKeuringen/ViewModels/AssignmentViewModel.cs
using OverDeRheinKraanKeuringen.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OverDeRheinKraanKeuringen.ViewModels
{
    public class AssignmentViewModel
    {
        public Assignment Assignment { get; set; }
   
        public List<CableChecklist> CableChecklists { get; set; }
    }
}

OverDeRheinKraanKeuringen/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OverDeRheinKraanKeuringen.Data;
using OverDeRheinKraanKeuringen.Models;

namespace OverDeRheinKraanKeuringen.Controllers
{
    public class AssignmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AssignmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Assignments
        public async Task<IActionResult> Index()
        {
            var x = await _context.Assignments.Include(m => m.CableChecklists).ToListAsync();
            return View(x);
        }

        // GET: Assignments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // GET: Assignments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,WorkInstruction,Date,CableSupplier,Observations,OperatingHours,Reason,SignatureDataUrl")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrWhiteSpace(assignment.SignatureDataUrl)) return BadRequest();

                var base64Signature = assignment.SignatureDataUrl.Split(",")[1];
                assignment.Signature = Convert.FromBase64String(base64Signature);
                
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assignment);
        }

        // GET: Assignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment == null)
            {
                return NotFound();
            }
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,WorkInstruction,Date,CableSupplier,Observations,Signature,OperatingHours,Reason")] Assignment assignment)
        {
            if (id != assignment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assignment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentExists(assignment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(assignment);
        }

        // GET: Assignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assignment = await _context.Assignments.Include(m => m.CableChecklists).Where(a => a.Id == id).FirstOrDefaultAsync();
            _context.Assignments.Remove(assignment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssignmentExists(int id)
        {
            return _context.Assignments.Any(e => e.Id == id);
        }
    }
}

OverDeRheinKraanKeuringen/Views/Assignments/Create.cshtml
@model OverDeRheinKraanKeuringen.Models.Assignment

@{
    ViewData["Title"] = "Create";
}

<h2>Nieuwe opdracht</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WorkInstruction" class="control-label"></label>
                <input asp-for="WorkInstruction" class="form-control" />
                <span asp-validation-for="WorkInstruction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CableSupplier" class="control-label"></label>
                <input asp-for="CableSupplier" class="form-control" />
                <span asp-validation-for="CableSupplier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observations" class="control-label"></label>
                <input asp-for="Observations" class="form-control" />
                <span asp-validation-for="Observations" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OperatingHours" class="control-label"></label>
                <input asp-for="OperatingHours" class="form-control" />
                <span asp-validation-for="OperatingHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reason" class="control-label"></label>
                <input asp-for="Reason" class="form-control" />
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Signature" class="control-label"></label>
                <canvas width="500" height="400" id="signature"
                        style="border:1px solid black">
                </canvas>
                <br />
                <button type="button" id="clear" class="btn btn-danger">Verwijder handtekening</button>
                <br />
                <input type="hidden" asp-for="@Model.SignatureDataUrl">
                <br />
            </div>
            <div class="form-group">
                <input type="submit" id="accept" value="Voeg nieuwe opdracht toe" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Terug naar lijst</a>
</div>

@section Scripts {
    <script src="~/js/signature_pad.min.js"></script>
    <script>
        $(function () {

            var canvas = document.querySelector('#signature');
            var pad = new SignaturePad(canvas);

            $('#accept').click(function () {
                var data = pad.toDataURL();

                $('#savetarget').attr('src', data);
                $('#SignatureDataUrl').val(data);
                pad.off();
            });

            $('#clear').click(function () {
                pad = new SignaturePad(canvas);
            })

        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

OverDeRheinKraanKeuringen/Views/Assignments/Delete.cshtml
@model OverDeRheinKraanKeuringen.Models.Assignment

@{
    ViewData["Title"] = "Delete";
}

<h2>Verwijder opdracht</h2>

<h3>Weet je zeker dat je deze opdracht wilt verwijderen?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkInstruction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkInstruction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CableSupplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CableSupplier)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OperatingHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OperatingHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Signature)
        </dt>
        <dd>
            @if (Model.Signature != null)
            {
                <img style="height:auto; width:100px" id="Image" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Signature))" />
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Verwijder" class="btn btn-danger" />
        <br />
        <br />
        <a asp-action="Index">Terug naar lijst</a>
    </form>
</div>

OverDeRheinKraanKeuringen/Views/Assignments/Details.cshtml
@model OverDeRheinKraanKeuringen.Models.Assignment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Opdracht</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WorkInstruction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WorkInstruction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CableSupplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CableSupplier)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OperatingHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OperatingHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reason)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reason)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Signature)
        </dt>
        <dd>
            @if (Model.Signature != null)
            {
                <img style="height:auto; width:100px" id="Image" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(Model.Signature))" />
            }
        </dd>
    </dl>
    @*
        <form asp-action="Edit" asp-route-id="@Model.Id" asp-controller="Assignments">
            <input type="submit" value="Wijzig" class="btn btn-success" />
            <br />
            <br />
            <a asp-action="Index">Terug naar lijst</a>
        </form>
    *@

    <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.Id">Wijzig</a>
    <br />
    <br />
    <a asp-controller="Assignments" asp-action="Index">Terug naar lijst</a>
</div>

OverDeRheinKraanKeuringen/Views/Assignments/Edit.cshtml
@model OverDeRheinKraanKeuringen.Models.Assignment

@{
    ViewData["Title"] = "Edit";
}

<h2>Wijzig</h2>

<h4>Opdracht</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="WorkInstruction" class="control-label"></label>
                <input asp-for="WorkInstruction" class="form-control" />
                <span asp-validation-for="WorkInstruction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CableSupplier" class="control-label"></label>
                <input asp-for="CableSupplier" class="form-control" />
                <span asp-validation-for="CableSupplier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observations" class="control-label"></label>
                <input asp-for="Observations" class="form-control" />
                <span asp-validation-for="Observations" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="OperatingHours" class="control-label"></label>
                <input asp-for="OperatingHours" class="form-control" />
                <span asp-validation-for="OperatingHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reason" class="control-label"></label>
                <input asp-for="Reason" class="form-control" />
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
            <!--This code can be used if you want to make it possible to change the signature later-->
            @*
            <div class="form-group">
                <label asp-for="Signature" class="control-label"></label>
                <canvas width="500" height="400" id="signature"
                        style="border:1px solid black">
                </canvas>
                <br />
                <button type="button" id="clear" class="btn btn-danger">Verwijder handtekening</button>
                <br />
                <input type="hidden" asp-for="@Model.SignatureDataUrl">
            </div>
            <br />
            *@
            <br />
            <br />
            <div class="form-group">
                <input type="submit" value="Bewaar wijzigingen" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Terug naar lijst</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OverDeRheinKraanKeuringen/Views/Assignments/Index.cshtml
@model IEnumerable<OverDeRheinKraanKeuringen.Models.Assignment>

@{
    ViewData["Title"] = "Index";
}

<h2>Opdrachten</h2>
<br />
<form>
    <button class="btn-success" asp-action="Create">Nieuwe opdracht</button>
</form>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                Opdrachtnr.
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CableSupplier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OperatingHours)
            </th>
            @*
            <th>
                @Html.DisplayNameFor(model => model.Signature)
            </th>
            *@
            <th></th>
        </tr>
    </thead>
    <tbody class="panel panel-default">
        @foreach (var item in Model)
        {
            int i = item.Id;

            <tr class="panel-heading">
                <td class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordionY" href="#collapse_@i">@i</a>
                </td>
                <td class="panel-title">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="panel-title">
                    @Html.DisplayFor(modelItem => item.CableSupplier)
                </td>
                <td class="panel-title">
                    @Html.DisplayFor(modelItem => item.OperatingHours)
                </td>
                @*
                <td class="panel-title">
                    @if(item.Signature != null) { 
                    <div class="Image" style="float:left; ">
                        <img style="height:auto; width:50px" id="Image" src="@String.Format("data:image/png;base64,{0}", Convert.ToBase64String(item.Signature))" />
                    </div>
                    }
                </td>
                *@
                <td>
                    <form>
                        <button class="btn-primary" asp-action="Details" asp-route-id=@item.Id.ToString()>Toon details</button>
                        <button style="margin-left:10px" class="btn-danger" asp-action="Delete" asp-route-id=@item.Id.ToString()>Verwijder</button>
                    </form>       
                </td>
            </tr>
            <tr>
                <td id="collapse_@i"class="panel-collapse collapse">
                    <div class="panel-body">
                        <partial name="~/Views/Shared/_AssignmentPartial.cshtml" model=item>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>