OverDeRheinKraanKeuringen/Controllers/CableChecklistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OverDeRheinKraanKeuringen.Data;
using OverDeRheinKraanKeuringen.Models;
using OverDeRheinKraanKeuringen.ViewModels;

namespace OverDeRheinKraanKeuringen.Controllers
{
    public class CableChecklistsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CableChecklistsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CableChecklists
        public async Task<IActionResult> Index()
        {
            var x = await _context.CableChecklists.Include(m => m.DamageTypes).ToListAsync();
            return View(x);
        }

        // GET: CableChecklists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cableChecklist = await _context.CableChecklists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cableChecklist == null)
            {
                return NotFound();
            }

            return View(cableChecklist);
        }

        // GET: CableChecklists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CableChecklists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CableChecklist,DamageTypeIds")] CableCheckListViewModel cableChecklistViewModel)
        {
            if (ModelState.IsValid)
            {

                List<DamageType> damageTypes = new List<DamageType>();

                foreach (var item in cableChecklistViewModel.DamageTypeIds)
                {
                    DamnType damnType;
                    Enum.TryParse(item, out damnType);

                    DamageType damageType = new DamageType { Type = damnType };
                    damageTypes.Add(damageType);
                }

                cableChecklistViewModel.CableChecklist.DamageTypes = damageTypes;

                _context.Add(cableChecklistViewModel.CableChecklist);
                await _context.SaveChangesAsync();
                return Redirect("~/Assignments/Index");
            }
            return View(cableChecklistViewModel);
        }

        //public async Task<IActionResult> Create([Bind("CableChecklist,DamageTypeIds")] CableCheckListViewModel cableChecklistViewModel)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        List<DamageType> damageTypes = new List<DamageType>();

        //        foreach (var item in cableChecklistViewModel.DamageTypeIds)
        //        {
        //            DamnType damnType;
        //            Enum.TryParse(item, out damnType);

        //            DamageType damageType = new DamageType { Type = damnType };
        //            damageTypes.Add(damageType);
        //        }

        //        cableChecklistViewModel.CableChecklist.DamageTypes = damageTypes;

        //        _context.Add(cableChecklistViewModel.CableChecklist);
        //        await _context.SaveChangesAsync();
        //        return Redirect("~/Assignments/Index");
        //        //return RedirectToAction(nameof(Index));
        //    }
        //    return View(cableChecklistViewModel);
        //}

        // GET: CableChecklists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cableChecklist = await _context.CableChecklists.FindAsync(id);
            if (cableChecklist == null)
            {
                return NotFound();
            }
            return View(cableChecklist);
        }

        // POST: CableChecklists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Breakage_6D,Breakage_30D,DamageOutside,DamageCorrosion,ReducedCableDiameter,PositionMeasuringPoints,DamageTotal")] CableChecklist cableChecklist)
        {
            if (id != cableChecklist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cableChecklist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CableChecklistExists(cableChecklist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cableChecklist);
        }

        // GET: CableChecklists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cableChecklist = await _context.CableChecklists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cableChecklist == null)
            {
                return NotFound();
            }

            return View(cableChecklist);
        }

        // POST: CableChecklists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cableChecklist = await _context.CableChecklists.Include(m => m.DamageTypes).Where(a => a.Id == id).FirstOrDefaultAsync();
            _context.CableChecklists.Remove(cableChecklist);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CableChecklistExists(int id)
        {
            return _context.CableChecklists.Any(e => e.Id == id);
        }
    }
}

OverDeRheinKraanKeuringen/Views/Shared/_AssignmentPartial.cshtml
@model OverDeRheinKraanKeuringen.Models.Assignment

<h4>Kabelchecklists</h4>
<form>
    <button class="btn-success" asp-controller="CableChecklists" asp-action="Create">Nieuwe checklist</button>
</form>
<br />
<br />
<div>
    @if (Model.CableChecklists.Count() != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Kabel-id
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="panel panel-default">
                @foreach (var item in Model.CableChecklists)
                {
                    <tr class="panel-heading">
                        <td class="panel-title">
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            <form>
                                <button class="btn-primary" asp-controller="CableChecklists" asp-action="Details" asp-route-id=@item.Id.ToString()>Toon details</button>
                                <button style="margin-left:10px" class="btn-danger" asp-controller="CableChecklists" asp-action="Delete" asp-route-id=@item.Id.ToString()>Verwijder</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Er zijn op dit moment nog geen kabelchecklists ingevoerd</p>
    }
</div>
















    @*
        <div>
            @if (Model.cableChecklists.Count() != 0)
            {
                foreach (var cableChecklist in Model.cableChecklists)
                {
                    int i = cableChecklist.Id;
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordionX" href="#collapse_@i">@i</a>
                            </h4>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>Er zijn op dit moment nog geen kabelchecklists ingevoerd</p>
            }
        </div>
    *@



    @*
        <div>


            @for (int i = 0; i.cableChecklists.Count(); i++)
            {

            }


            @if (Model != null)
            {
                foreach (var cableChecklist in Model)
                {
                    int i = cableChecklist.Id;
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordionX" href="#collapse_@i">@i</a>
                            </h4>
                        </div>
                    </div>
                }
            }
            else
            {
                <p>Er zijn op dit moment nog geen kabelchecklists ingevoerd</p>
            }

        </div>
    *@



    @*<table class="my-table">


            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Niveau)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Naam)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Duur)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Werkvorm)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().Topic.Certificeringen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Topics.FirstOrDefault().TopicVoortgang)
                </th>
                <th></th>
            </tr>
            @foreach (var topic in Model.)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => topic.Topic.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => topic.Topic.Niveau.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => topic.Topic.Naam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => topic.Topic.Duur.Eenheid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => topic.Topic.Werkvorm.Naam)
                    </td>
                    <td>
                        @foreach (var cert in topic.Topic.Certificeringen)
                        {
                            @Html.DisplayFor(modelItem => cert.Naam)
                        }
                    </td>
                    <td>

                        @Html.DropDownListFor(modelItem => topic.TopicVoortgang, new SelectList(Enum.GetValues(typeof(StudentenVolgSysteem.Models.Voortgang))), new { htmlAttributes = new { @class = "form-control" } })

                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "Topics", new { id = topic.TopicId, returnUrl = this.Request.RawUrl }, null)
                    </td>
                </tr>
            }
        </table>*@






    @*

        @if (Model != null)
        {
            foreach (var cableChecklist in Model)
            {
                int i = cableChecklist.Id;
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordionX" href="#collapse_@i">@i</a>
                        </h4>
                    </div>
                </div>
            }

    *@




    @*
        For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
    *@


    <!--
    <div class="card">
        <div class="card-header" id="headingOne">
            <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Collapsible Group Item #1
                </button>
            </h5>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
                <p>Hey there!</p>
            </div>
        </div>
    </div>
    -->
    @*
        @model List<OverDeRheinKraanKeuringen.Models.Assignment>

        @{
            ViewData["Title"] = "Home Page";
        }

        <br />
        <h2>Opdrachten</h2>
        <br />
        <form>
            <button formaction="/Assignments/Create">Nieuwe opdracht</button>
        </form>
        <br />
        <br />
        @<div class="bs-example">
            <div class="panel-group" id="accordionY">
                @
            <ejs-accordion id="defaultAccordion" expandMode="Single">
                <e-accordion-accordionitems>
                    @if (Model != null)
                    {
                        //int i = 1;
                        foreach (var assigment in Model)
                        {
                            <partial name="_AssignmentPartial" for="@assigment" />
                        }
                    }
                    else
                    {
                        <p>Er zijn op dit moment geen opdrachten ingevoerd</p>
                    }
                    @* <e-accordion-accordionitem header="JavaScript" content="JavaScript (JS) is an interpreted computer programming language.It was originally implemented as part of web browsers so that client-side scripts could interact with the user, control the browser, communicate asynchronously, and alter the document content that was displayed.More recently, however, it has become common in both game development and the creation of desktop applications."></e-accordion-accordionitem>@

                            </e-accordion-accordionitems>
                        </ejs-accordion>
                        @</div>
                            </div>@


                        <!--
                        <div id="accordion">
                            @foreach (AssignmentModel assignmentModel in Model)
                            {
                                @TODO Meegeven assignment aan partial

                            }@
                        </div>
                        -->
    *@

OverDeRheinKraanKeuringen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Over de Rhein Kraankeuringen</title>

    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <!-- Syncfusion Essential JS 2 Scripts -->
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="" asp-action="" class="navbar-brand">Over De Rhein Kraankeuringen</a>
            </div>
      
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <br />
        <footer>
            <p>&copy; 2020 - Over de Rhein Kraankeuringen B.V.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <ejs-scripts></ejs-scripts>
    @RenderSection("Scripts", required: false)
</body>
</html>